package:
  name: dbt_utils
  version: 1.0

source:
  fn: master.zip
  url: https://github.com/fishtown-analytics/dbt-utils/archive/master.zip

build:
  number: 0

# test:
#   commands:
#     - wget --help

about:
  home: https://github.com/fishtown-analytics/dbt-utils
  license: Apache 2
